name: Publish images to registry

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release Tag
        uses: actions/checkout@v3
        with:
          ref ${{ github.event.release.tag_name }}

      - name: Validate Release Tag
        run: |
          # Extract tag name without 'v' prefix
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#v}
          
          echo "version=$VERSION" >> $GITHUB_ENV
          
          # Check if the version (extracted from the tag name) is a valid semantic version without pre-release or metadata
          # If so, we will publish this as the latest release on DockerHub
          LATEST='false'
          if echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            LATEST='true'
          fi
          
          echo "latest=$LATEST" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          TAG: ${{ env.version }}
          LATEST: ${{ env.latest }}
        run: |
          make push-images
